name: coroutines
description: Library support for Dart coroutines structured async with multiplatform support.
version: 1.0.0
homepage: https://github.com/eitanliu/dart_coroutines
repository: https://github.com/eitanliu/dart_coroutines

environment:
  sdk: '>=2.18.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
